service: tae-website-mailer 
app: tae-website-mailer
tenant: mhopard
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]

functions:
  taeStaticMailer:
    handler: handler.taeStaticMailer
    events:
      - http:
          method: post
          path: tae-website-mailer 
          cors: true